language: java

branches:
  only:
    - master
    - /^release.*$/

jdk:
  - oraclejdk11

deploy:
  - provider: script
    script: gradlew publishReleasePublicationToBintrayRepository
    on:
      branch: master