language: java

branches:
  only:
    - master
    - develop
    - /^release.*$/

jdk:
  - oraclejdk11

deploy:
  - provider: script
    script: ./gradlew artifactoryPublish
    on:
      branch: master